name: Build project for beta-Branch

on:
  push:
    branches: ['beta']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: |
          rm -rf ./build
          npm run build
      
      - name: Commit build output
        run: |
          git config --local user.email "mondula@users.noreply.github.com"
          git config --local user.name "Build Bot"
          git add -f ./build
          git commit -m "Build project"
          git fetch origin
          git rebase --strategy-option=theirs origin/beta
          git push
